### ISSUE TITLE
Plant growth not growing during the sunlight

### ISSUE THREAD

**Issue by unlimitedgithub** [Taranchuk/PurpleIvy#3]
Plant says its growing but it remains at 5%

**Comment by unlimitedgithub** [comment]
<fertilityMin>0.001</fertilityMin>
			<fertilitySensitivity>0.3</fertilitySensitivity>
			<growDays>0.5</growDays>
			<harvestWork>40</harvestWork>
      <dieIfLeafless>false</dieIfLeafless>
      <neverBlightable>true</neverBlightable>

**Comment by unlimitedgithub** [comment]
Found something that may be helpful, was able to get the plant to grow to maturity by changing 
	<tickerType>Rare</tickerType>    to 	<tickerType>Long</tickerType>
This does seem to break plant spread, it no longer grows or expands outwards

**Comment by unlimitedgithub** [comment]
<thingClass>PurpleIvy.Plant_Ivy</thingClass>    
	<tickerType>Long</tickerType>

**Comment by Taranchuk** [comment]
Solved
